# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 08:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20171128_1705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='boardNm',
            new_name='title_ko',
        ),
    ]
