# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_post_boardcd'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Board',
        ),
        migrations.AddField(
            model_name='post',
            name='boardcd',
            field=models.TextField(default='free', max_length=20),
        ),
    ]
