# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20171124_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='boardcd',
            field=models.CharField(default='free', max_length=20),
        ),
    ]
