# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 09:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_post_hit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boardNm', models.TextField(default='free')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='hit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='boardcd',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.Board'),
            preserve_default=False,
        ),
    ]
